### PR TITLE
Update Nginx to 1.9.5

### PR DESCRIPTION
**Pull request by jingweno**
* Update Nginx to 1.9.5
* Use Docker to build Nginx for cedar-14 and cedar
* Clean up build script

### CODE REVIEW

**Comment by mikehale** [comment]
I was able to build this locally... but now I'm not sure what to do with the build artifacts.

**Comment by jingweno** [comment]
@mikehale You could either try the build binaries on a server or run them in the container:

```
$ make shell
$ ./bin/nginx-cedar-14
```

**Comment by jingweno** [comment]
I added instruction on testing the builds in the container: https://github.com/heroku/heroku-buildpack-nginx/commit/21e84d4ff0c147d3754fadb7a06b69a06a426991.

**Pull request merged**
